model_name: husky
cmd_topic_name: /husky_velocity_controller/cmd_vel

initial:
  x: 3.0
  y: 9.0
  phi: -1.0
   
target:
  x: -3.0
  y: -10.0  
  phi: 1.0

########################## YOU CAN CHANGE ANY PARAM BELOW ####################
###  you can modify the values below
###  you can also define maximum acceleration/deceleration, etc 

update_frequency: 500
min_distance_to_obstacles: 1.0
fbk_topic_name: /gazebo/model_states
sensor_topic_name: /front/scan

limit:
  speed: 0.5 
  omega: 0.5  