target1: [0.5, 0.5, 0.5]
target2: [1.0, 1.0, 1.0] 
target3: [-0.5, 0.5, 0.3]
target_time: 5
orientation: [0.0, 0.0, 0.0]
sub_topic: /gen3/joint_states
pub_topic: /gen3/joint_group_position_controller/command